XceedTask/Controllers/Components/AdminSlideViewComponent.cs
namespace XceedTask.Controllers.Components;

public class AdminSlideViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View();
    }
}

XceedTask/Views/Shared/_ErrorLayout.cshtml
@{
    var lang = HttpContextAccessor.HttpContext?.Request.Cookies["lang"] ?? "En";
    var mode = HttpContextAccessor.HttpContext?.Request.Cookies["mode"] ?? "Dark";
    var title = (ViewData["Title"] == null) ? (lang == "En" ? "Admin Dashboard" : "لوحة تحكم المسؤول") : ViewData["Title"];

}
<!doctype html>
<html lang="en" dir="ltr">

<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Sash – Bootstrap 5  Admin & Dashboard Template">
    <meta name="author" content="Spruko Technologies Private Limited">
    <meta name="keywords" content="admin,admin dashboard,admin panel,admin template,bootstrap,clean,dashboard,flat,jquery,modern,responsive,premium admin templates,responsive admin,ui,ui kit.">

    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/brand/favicon.ico">

    <!-- TITLE -->
    <title>Sash – Bootstrap 5 Admin & Dashboard Template</title>

    <!-- BOOTSTRAP CSS -->
    <link id="style" href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- STYLE CSS -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- Plugins CSS -->
    <link href="~/assets/css/plugins.css" rel="stylesheet">

    <!--- FONT-ICONS CSS -->
    <link href="~/assets/css/icons.css" rel="stylesheet">

    <!-- INTERNAL Switcher css -->
    <link href="~/assets/switcher/css/switcher.css" rel="stylesheet">
    <link href="~/assets/switcher/demo.css" rel="stylesheet">

</head>

<body class="login-img">

<!-- BACKGROUND-IMAGE -->
<div class="">
    <!-- Error -->
@RenderBody()

</div>
<!-- BACKGROUND-IMAGE -->

<!-- JQUERY JS -->
<script src="~/assets/js/jquery.min.js"></script>

<!-- BOOTSTRAP JS -->
<script src="~/assets/plugins/bootstrap/js/popper.min.js"></script>
<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>

<!-- Perfect SCROLLBAR JS-->
<script src="~/assets/plugins/p-scroll/perfect-scrollbar.js"></script>

<!-- Color Theme js -->
<script src="~/assets/js/themeColors.js"></script>

<!-- CUSTOM JS -->
<script src="~/assets/js/custom.js"></script>

<!-- Custom-switcher -->
<script src="~/assets/js/custom-swicher.js"></script>

<!-- Switcher js -->
<script src="~/assets/switcher/js/switcher.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

XceedTask/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en" dir="ltr">

<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Sash – Bootstrap 5  Admin & Dashboard Template">
    <meta name="author" content="Spruko Technologies Private Limited">
    <meta name="keywords" content="admin,admin dashboard,admin panel,admin template,bootstrap,clean,dashboard,flat,jquery,modern,responsive,premium admin templates,responsive admin,ui,ui kit.">

    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/brand/favicon.ico">

    <!-- TITLE -->
    <title>XceedTask - login</title>

    <!-- BOOTSTRAP CSS -->
    <link id="style" href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- STYLE CSS -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- Plugins CSS -->
    <link href="~/assets/css/plugins.css" rel="stylesheet">

    <!--- FONT-ICONS CSS -->
    <link href="~/assets/css/icons.css" rel="stylesheet">

    <!-- INTERNAL Switcher css -->
    <link href="~/assets/switcher/css/switcher.css" rel="stylesheet">
    <link href="~/assets/switcher/demo.css" rel="stylesheet">

</head>

<body class="app sidebar-mini ltr login-img">

<!-- BACKGROUND-IMAGE -->
<div class="">

    <!-- GLOABAL LOADER -->
    <div id="global-loader">
        <img src="~/assets/images/loader.svg" class="loader-img" alt="Loader">
    </div>
    <!-- /GLOABAL LOADER -->
    <!-- PAGE -->
    <div class="page">
        <div class="">
            <!-- Theme-Layout -->
            <!-- CONTAINER OPEN -->
            <div class="col col-login mx-auto mt-7">
                <div class="text-center">
                    <a href="javascript:;">
                        <img src="~/assets/images/brand/logo-white.png" class="header-brand-img" alt="">
                    </a>
                </div>
            </div>

            @RenderBody()
            <!-- CONTAINER CLOSED -->
        </div>
    </div>
    <!-- End PAGE -->

</div>
<!-- BACKGROUND-IMAGE CLOSED -->
<!-- JQUERY JS -->
<script src="~/assets/js/jquery.min.js"></script>

<!-- BOOTSTRAP JS -->
<script src="~/assets/plugins/bootstrap/js/popper.min.js"></script>
<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>

<!-- SHOW PASSWORD JS -->
<script src="~/assets/js/show-password.min.js"></script>

<!-- GENERATE OTP JS -->
<script src="~/assets/js/generate-otp.js"></script>

<!-- Perfect SCROLLBAR JS-->
<script src="~/assets/plugins/p-scroll/perfect-scrollbar.js"></script>

<!-- Color Theme js -->
<script src="~/assets/js/themeColors.js"></script>

<!-- CUSTOM JS -->
<script src="~/assets/js/custom.js"></script>

<!-- Custom-switcher -->
<script src="~/assets/js/custom-swicher.js"></script>

<!-- Switcher js -->
<script src="~/assets/switcher/js/switcher.js"></script>
@await RenderSectionAsync("Scripts", false)
</body>

</html>

XceedTask/Views/Shared/_MainLayout.cshtml
@{
    var currentController = ViewContext.RouteData.Values["Controller"]?.ToString();
    var currentAction = ViewContext.RouteData.Values["Action"]?.ToString();
    var url = Url.Action(currentAction, currentController);
    var userData = UserManager.FindByNameAsync(User.Identity?.Name ?? string.Empty).Result ?? new ApplicationUser();
    var lang = HttpContextAccessor.HttpContext?.Request.Cookies["lang"] ?? "En";
    var mode = HttpContextAccessor.HttpContext?.Request.Cookies["mode"] ?? "Dark";
    var title = ViewData["Title"] == null ? lang == "En" ? "Admin Dashboard" : "لوحة تحكم المسؤول" : ViewData["Title"];
}
<!doctype html>
<html lang="@(lang == "En" ? "en" : "ar")" dir="ltr">

<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Sash – Bootstrap 5  Admin & Dashboard Template">
    <meta name="author" content="Spruko Technologies Private Limited">
    <meta name="keywords"
          content="admin,admin dashboard,admin panel,admin template,bootstrap,clean,dashboard,flat,jquery,modern,responsive,premium admin templates,responsive admin,ui,ui kit.">

    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/brand/favicon.ico">

    <!-- TITLE -->
    <title>@title </title>

    <!-- BOOTSTRAP CSS -->
    <link id="style" href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- STYLE CSS -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- Plugins CSS -->
    <link href="~/assets/css/plugins.css" rel="stylesheet">

    <!--- FONT-ICONS CSS -->
    <link href="~/assets/css/icons.css" rel="stylesheet">

    <!-- INTERNAL Switcher css -->
    <link href="~/assets/switcher/css/switcher.css" rel="stylesheet">
    <link href="~/assets/switcher/demo.css" rel="stylesheet">

    @await RenderSectionAsync("Styles", false)
    <style>
        table.table-bordered.dataTable th, table.table-bordered.dataTable td {
          
            vertical-align: middle;
            text-align: center;
        }

        .hover-image {
            width: 100%;
            height: 100%;
            max-width: 75%;
            transition: transform 0.3s ease; /* Add a smooth transition effect */
        }

            .hover-image:hover {
                transform: scale(1.2); /* Adjust the scale factor for the desired zoom level */
                cursor: pointer; /* Add a pointer cursor on hover */
            }
    </style>
</head>

<body class="@(mode == "Dark" ? "dark-mode" : "light-mode") app sidebar-mini @(lang == "En" ? "ltr" : "rtl") ">


<!-- GLOBAL-LOADER -->
<div id="global-loader">
    <img src="~/assets/images/loader.svg" class="loader-img" alt="Loader">
</div>
<!-- /GLOBAL-LOADER -->

<!-- PAGE -->
<div class="page">
    <div class="page-main">

        <div class="main-content app-content mt-0">
            <div class="side-app">

                <!-- CONTAINER -->
                <div class="main-container container-fluid">
                    <partial name="DashboardPartials/_NavDashboardPartial"></partial>

                    @await Component.InvokeAsync("AdminSlide")

                    <!-- PAGE-HEADER -->
                    <partial name="DashboardPartials/_PageHeaderPartial" model="@title"></partial>
                    <!-- PAGE-HEADER END -->

                    @RenderBody()

                </div>
            </div>
        </div>
    </div>


    <!-- FOOTER -->
    <footer class="footer">
        <div class="container">
            <div class="row align-items-center flex-row-reverse">
                <div class="col-md-12 col-sm-12 text-center">
                        Copyright © <span id="year"></span> <a href="https://www.linkedin.com/in/mahmoud-sabry-khuzaim/">Mahmoud Sabry ❤️</a>.All rights reserved
                    </div>
            </div>
        </div>
    </footer>
    <!-- FOOTER END -->
</div>
<!-- BACK-TO-TOP -->
<a href="#top" id="back-to-top">
    <i class="fa fa-angle-up"></i>
</a>

<!-- JQUERY JS -->
<script src="~/assets/js/jquery.min.js"></script>

<!-- BOOTSTRAP JS -->
<script src="~/assets/plugins/bootstrap/js/popper.min.js"></script>
<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>

<!-- INPUT MASK JS-->
<script src="~/assets/plugins/input-mask/jquery.mask.min.js"></script>

<!-- SPARKLINE JS-->
<script src="~/assets/js/jquery.sparkline.min.js"></script>

<!-- Sticky js -->
<script src="~/assets/js/sticky.js"></script>

<!-- CHART-CIRCLE JS-->
<script src="~/assets/js/circle-progress.min.js"></script>



<!-- SIDEBAR JS -->
<script src="~/assets/plugins/sidebar/sidebar.js"></script>

<!-- Perfect SCROLLBAR JS-->
<script src="~/assets/plugins/p-scroll/perfect-scrollbar.js"></script>
<script src="~/assets/plugins/p-scroll/pscroll.js"></script>
<script src="~/assets/plugins/p-scroll/pscroll-1.js"></script>

<!-- INTERNAL CHARTJS CHART JS-->
<script src="~/assets/plugins/chart/Chart.bundle.js"></script>
<script src="~/assets/plugins/chart/utils.js"></script>

<!-- INTERNAL SELECT2 JS -->
<script src="~/assets/plugins/select2/select2.full.min.js"></script>
<script src="~/assets/js/select2.js"></script>

<!-- INTERNAL Data tables js-->
<script src="~/assets/plugins/datatable/js/jquery.dataTables.min.js"></script>
<script src="~/assets/plugins/datatable/js/dataTables.bootstrap5.js"></script>
<script src="~/assets/plugins/datatable/dataTables.responsive.min.js"></script>

<!-- INTERNAL APEXCHART JS -->
<script src="~/assets/js/apexcharts.js"></script>
<script src="~/assets/plugins/apexchart/irregular-data-series.js"></script>

<!-- INTERNAL Flot JS -->
<script src="~/assets/plugins/flot/jquery.flot.js"></script>
<script src="~/assets/plugins/flot/jquery.flot.fillbetween.js"></script>
<script src="~/assets/plugins/flot/chart.flot.sampledata.js"></script>
<script src="~/assets/plugins/flot/dashboard.sampledata.js"></script>

<!-- INTERNAL Vector js -->
<script src="~/assets/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js"></script>
<script src="~/assets/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>

<!-- SIDE-MENU JS-->
<script src="~/assets/plugins/sidemenu/sidemenu.js"></script>

<!-- TypeHead js -->
<script src="~/assets/plugins/bootstrap5-typehead/autocomplete.js"></script>
<script src="~/assets/js/typehead.js"></script>

<!-- INTERNAL INDEX JS -->
<script src="~/assets/js/index1.js"></script>

<!-- Color Theme js -->
<script src="~/assets/js/themeColors.js"></script>

<!-- CUSTOM JS -->
<script src="~/assets/js/custom.js"></script>

<!-- Custom-switcher -->
<script src="~/assets/js/custom-swicher.js"></script>

<!-- Switcher js -->
<script src="~/assets/switcher/js/switcher.js"></script>

<!-- DATA TABLE JS-->
<script src="~/assets/plugins/datatable/js/jquery.dataTables.min.js"></script>
<script src="~/assets/plugins/datatable/js/dataTables.bootstrap5.js"></script>
<script src="~/assets/plugins/datatable/js/dataTables.buttons.min.js"></script>
<script src="~/assets/plugins/datatable/js/buttons.bootstrap5.min.js"></script>
<script src="~/assets/plugins/datatable/js/jszip.min.js"></script>
<script src="~/assets/plugins/datatable/pdfmake/pdfmake.min.js"></script>
<script src="~/assets/plugins/datatable/pdfmake/vfs_fonts.js"></script>
<script src="~/assets/plugins/datatable/js/buttons.html5.min.js"></script>
<script src="~/assets/plugins/datatable/js/buttons.print.min.js"></script>
<script src="~/assets/plugins/datatable/js/buttons.colVis.min.js"></script>
<script src="~/assets/plugins/datatable/dataTables.responsive.min.js"></script>
<script src="~/assets/plugins/datatable/responsive.bootstrap5.min.js"></script>
<script src="~/assets/js/table-data.js"></script>

@await RenderSectionAsync("Scripts", false)
</body>

</html>